name: CI (All)

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-ci:
    uses: halberto2387/GroundedCounselling/.github/workflows/api-ci.yml@main
  web-ci:
    uses: halberto2387/GroundedCounselling/.github/workflows/web-ci.yml@main
