name: CI (All)

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  api-ci:
    uses: ./.github/workflows/api-ci.yml
    secrets: inherit
  web-ci:
    uses: ./.github/workflows/web-ci.yml
    secrets: inherit
