name: Web CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - '.github/workflows/web-ci.yml'

defaults:
  run:
    working-directory: .

jobs:
  web-ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Lint packages
      run: pnpm lint
      
    - name: Type check
      run: pnpm type-check
      
    - name: Build packages
      run: pnpm build
      
    - name: Run tests
      run: pnpm test
      env:
        CI: true
        
    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        fail_ci_if_error: false